#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
. /lib/cryptsetup/functions

# Check whether cryptroot hook has installed decrypt_gnupg_sc script
if [ ! -x ${DESTDIR}/lib/cryptsetup/scripts/decrypt_gnupg_sc ] ; then
    exit 0
fi

# Hooks for loading Gnupg software and key into the initramfs
copy_keys() {
    crypttab_parse_options
    if [ "${CRYPTTAB_OPTION_keyscript-}" = "/lib/cryptsetup/scripts/decrypt_gnupg_sc" ]; then
        if [ -f "$CRYPTTAB_KEY" ]; then
            keydir=$(dirname ${CRYPTTAB_KEY})
            copy_file keyfile "$CRYPTTAB_KEY"
            copy_file pubring "${keydir}/pubring.gpg"
            for private_key in ${keydir}/private-keys-v1.d/*; do
                copy_file private_key "${private_key}"
            done
        else
            cryptsetup_message "ERROR: Target $CRYPTTAB_NAME has a non-existing key file $CRYPTTAB_KEY"
            RV=1
        fi
    fi
}

RV=0
crypttab_foreach_entry copy_keys

# Install directories needed by smartcard reading daemon, command, and
# key-script
mkdir -p -- "$DESTDIR/etc/opensc" "$DESTDIR/usr/lib/pcsc" "$DESTDIR/var/run" "$DESTDIR/tmp"

# Install pcscd daemon, drivers, conf file, and include libgcc as well since
# pcscd utilizes pthread_cancel
copy_exec /usr/sbin/pcscd
LIB_DIR="/lib/$(uname -m)-linux-gnu"
find -L "$LIB_DIR" -maxdepth 1 \( -name 'libgcc_s.*' -o -name 'libusb-*.so*' \) -type f | while read so; do
    copy_exec "$so"
done

USR_LIB_DIR="/usr/lib/$(uname -m)-linux-gnu"
find -L "$USR_LIB_DIR" -maxdepth 1 \( -name 'libpcsclite.so*' \) -type f | while read so; do
    copy_exec "$so"
done

cp -rt "$DESTDIR/usr/lib" /usr/lib/pcsc
cp -t "$DESTDIR/etc" /etc/reader.conf 2>/dev/null || true
cp -t "$DESTDIR/etc" /etc/libccid_Info.plist

# Install common needed binaries
copy_exec /usr/bin/dirname

# Install gnupg software
copy_exec /usr/bin/gpg
copy_exec /usr/bin/gpg-agent
copy_exec /usr/lib/gnupg/scdaemon

exit $RV
